WebApplicationContoso/Controllers/CategorieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplicationContoso.Models;

namespace WebApplicationContoso.Controllers
{
    public class CategorieController : Controller
    {


        public ActionResult GetDetails(String Name)
        {
            return View();
        }
        // GET: Fournisseurs
        public ActionResult Add()
        {
            return View();//(Content("HelloFournisseurs"));
        }

        public ActionResult Delete()
        {
            return View();//(Content("HelloFournisseurs"));
        }

        public ActionResult Search(String Name)
        {
            var Cat = new CategorieModel
            {
                CategoryName = "Test",
                Description = "Test"
            };

            return View();//(Content("HelloFournisseurs"));
        }

        public ActionResult Modify(CategorieModel m)
        {
            return View(m);
        }

        public ActionResult List()
        {
            IEnumerable<CategorieModel> c = new List<CategorieModel>();
            return View(c);
        }
    }
}

WebApplicationContoso/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplicationContoso.Models;

namespace WebApplicationContoso.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult GetDetails(String Name) {
            ProductModel c = new ProductModel();
            return View(c);
        }
        
        public ActionResult Add()
        {
            ProductModel c = new ProductModel();
            return View(c);//(Content("HelloFournisseurs"));
        }

        [HttpPost]
        public ActionResult Add(ProductModel c)
        {
            //Ajout du modèle à la bd
            ServiceReferenceNW.NorthWindServiceClient client = new ServiceReferenceNW.NorthWindServiceClient();

            return RedirectToAction("Add");//(Content("HelloFournisseurs"));
        }

        public ActionResult Delete()
        {
            ProductModel c = new ProductModel();
            return View(c);//(Content("HelloFournisseurs"));
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            ServiceReferenceNW.NorthWindServiceClient client = new ServiceReferenceNW.NorthWindServiceClient();
            //client.Delete(id);
            ProductModel c = new ProductModel();
            return View();//(Content("HelloFournisseurs"));
        }

        public ActionResult Search()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(String Nom)
        {
            ServiceReferenceNW.NorthWindServiceClient client = new ServiceReferenceNW.NorthWindServiceClient();
            //ProductMode m = client.Search(Nom)
            //return RedirectToAction(GetDetails(m));
            return RedirectToAction("GetDetails");
        }

        public ActionResult Modify() {

            //DB.get(m);
            ProductModel c = new ProductModel();
            return View(c);
        }

        [HttpPost]
        public ActionResult Modify(ProductModel c)
        {
            ServiceReferenceNW.NorthWindServiceClient client = new ServiceReferenceNW.NorthWindServiceClient();
            //client.Update(c);
            return View(c);
        }

        public ActionResult List() {
            IEnumerable<ProductModel> c = new List<ProductModel>();
            return View(c);
        }
    }
}

WebApplicationContoso/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        #menu ul {
         margin:0;
         padding:0;
         list-style-type:none;
         text-align:center;
         }

        .big {
            font-style:normal;
            font-weight:bold;
            font-size:15px;
            color:yellow;

        }
    
    </style>
</head>
<body>
    
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Contoso_NorthWind", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="big">@Html.ActionLink("Produit", "List", "Product")</li>
                    
                        <li>@Html.ActionLink("Add", "Add", "Product")</li>
                        <li>@Html.ActionLink("Search", "Search", "Product")</li>
                    
                    <li class="big">@Html.ActionLink("Categories", "List", "Categorie")</li>
                    
                        <li>@Html.ActionLink("Ajout", "Add", "Categorie")</li>
                        <li>@Html.ActionLink("Search", "Search", "Categorie")</li>
                    
                    <li class="big">@Html.ActionLink("Fournisseurs", "List", "Fournisseurs")</li>
                    
                        <li>@Html.ActionLink("Add", "Add", "Fournisseurs")</li>
                        <li>@Html.ActionLink("Search", "Search", "Fournisseurs")</li>
                    

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>